name: Build iStoreOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          istoreos/dl
          istoreos/staging_dir
        key: ${{ runner.os }}-istoreos-cache-${{ hashFiles('feeds.conf') }}
        restore-keys: |
          ${{ runner.os }}-istoreos-cache-

    - name: Remove existing istoreos directory if it exists
      run: rm -rf istoreos

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc g++ make git unzip libncurses5-dev zlib1g-dev

    - name: Clone iStoreOS
      run: |
        git clone --depth=1 -b istoreos-24.10 https://github.com/istoreos/istoreos.git istoreos

    - name: Update feeds
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cp feeds.conf istoreos/
        cd istoreos
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure
      run: |
        cd istoreos
        make defconfig
        echo "CONFIG_TARGET_x86_64=y" >> .config
        echo "CONFIG_TARGET_x86_64_Generic=y" >> .config
        echo "CONFIG_PACKAGE_kmod-rtw8852be=y" >> .config
        echo "CONFIG_TARGET_ROOTFS_PARTSIZE=50" >> .config
        echo "CONFIG_TARGET_IMAGES_GPT_PARTED='set 1 msdos 1'" >> .config
        echo "CONFIG_TARGET_IMAGES_GPT_PARTED_SIZE=2000" >> .config
        echo "CONFIG_TARGET_IMAGES_EXT4=y" >> .config
        echo "CONFIG_TARGET_IMAGES_EFI=y" >> .config

    - name: Build firmware
      run: |
        cd istoreos
        make -j$(( $(nproc) + 1 )) V=s

    - name: Check build directory
      run: |
        cd istoreos
        ls -R ./bin/targets/

    - name: Check for built artifacts
      run: |
        cd istoreos
        ls ./bin/targets/x86/64/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: istoreos-firmware
        path: istoreos/bin/targets/x86/64/*-x86-64-generic-ext4-combined-efi.img.gz
        if-no-files-found: error
